<?php

namespace ContainerBRxavYd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6hM5EZQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6hM5EZQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6hM5EZQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'project' => ['privates', '.errored..service_locator.6hM5EZQ.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.6hM5EZQ": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'project' => 'App\\Entity\\Project',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
        ]);
    }
}
