<?php

namespace ContainerBRxavYd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__383L6eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..383L6e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..383L6e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProjectController::delete' => ['privates', '.service_locator.6hM5EZQ', 'get_ServiceLocator_6hM5EZQService', true],
            'App\\Controller\\ProjectController::edit' => ['privates', '.service_locator.6hM5EZQ', 'get_ServiceLocator_6hM5EZQService', true],
            'App\\Controller\\ProjectController::index' => ['privates', '.service_locator.Zo_U4ST', 'get_ServiceLocator_ZoU4STService', true],
            'App\\Controller\\ProjectController::new' => ['privates', '.service_locator.Zo_U4ST', 'get_ServiceLocator_ZoU4STService', true],
            'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.1.2RqhU', 'get_ServiceLocator_1_2RqhUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProjectController:delete' => ['privates', '.service_locator.6hM5EZQ', 'get_ServiceLocator_6hM5EZQService', true],
            'App\\Controller\\ProjectController:edit' => ['privates', '.service_locator.6hM5EZQ', 'get_ServiceLocator_6hM5EZQService', true],
            'App\\Controller\\ProjectController:index' => ['privates', '.service_locator.Zo_U4ST', 'get_ServiceLocator_ZoU4STService', true],
            'App\\Controller\\ProjectController:new' => ['privates', '.service_locator.Zo_U4ST', 'get_ServiceLocator_ZoU4STService', true],
            'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.1.2RqhU', 'get_ServiceLocator_1_2RqhUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProjectController::delete' => '?',
            'App\\Controller\\ProjectController::edit' => '?',
            'App\\Controller\\ProjectController::index' => '?',
            'App\\Controller\\ProjectController::new' => '?',
            'App\\Controller\\ProjectController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProjectController:delete' => '?',
            'App\\Controller\\ProjectController:edit' => '?',
            'App\\Controller\\ProjectController:index' => '?',
            'App\\Controller\\ProjectController:new' => '?',
            'App\\Controller\\ProjectController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
