<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBRxavYd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBRxavYd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBRxavYd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBRxavYd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBRxavYd\App_KernelDevDebugContainer([
    'container.build_hash' => 'BRxavYd',
    'container.build_id' => '98754f0e',
    'container.build_time' => 1679037747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBRxavYd');
