<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'app_lucky' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky']], [], [], []],
    'app_project_index' => [[], ['_controller' => 'App\\Controller\\ProjectController::index'], [], [['text', '/project/']], [], [], []],
    'app_project_new' => [[], ['_controller' => 'App\\Controller\\ProjectController::new'], [], [['text', '/project/new']], [], [], []],
    'app_project_show' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/project']], [], [], []],
    'app_project_edit' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/project']], [], [], []],
    'app_project_delete' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/project']], [], [], []],
];
